spring:
  application:
    name: reservation-platform
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reservation_platform}
    username: ${DB_USERNAME:reservation_app}
    password: ${DB_PASSWORD:}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 90MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  tomcat:
    max-swallow-size: 100MB

security:
  jwt:
    secret: ${JWT_SECRET:}

rpb:
  local-auth:
    enabled: false
