package com.rpb.reservation.customerauth.application;

public enum CustomerAuthError {
    REQUEST_INVALID,
    ACCOUNT_DISABLED,
    EMAIL_CHANNEL_NOT_CONFIGURED,
    EMAIL_DELIVERY_FAILED,
    CODE_EXPIRED,
    CODE_MISMATCH,
    UNAUTHENTICATED,
    PROVIDER_NOT_CONFIGURED,
    PROVIDER_UNSUPPORTED,
    PROVIDER_TOKEN_INVALID,
    PERSISTENCE_ERROR
}
